name: Build Flet APK

on:
  push:
    branches:
      - main  # Você pode mudar para a branch que deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          pip install pyinstaller

      - name: Build APK with PyInstaller
        run: |
          pyinstaller --name="appflet" --onefile --windowed main.py  # Substitua "main.py" pelo nome do seu arquivo principal

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: appflet-apk
          path: dist/appflet.apk  # Substitua pelo caminho correto do APK