name: Build Flet APK

on:
  push:
    branches:
      - main  # Monitora o branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer init  # Inicializa o arquivo buildozer.spec
          sed -i 's/# source.include_exts/\1 py,kv,png,jpg,ttf' buildozer.spec
          sed -i 's/# source.include_patterns/\1 *.py' buildozer.spec
          sed -i 's/# source.exclude_dirs/\1 .github, .vscode, tests' buildozer.spec
          sed -i 's/# title =/\1 MyFletApp/' buildozer.spec  # Nome do app
          sed -i 's/# package.domain/\1 com.example.flet/' buildozer.spec
          buildozer -v android debug  # Gera o APK

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: appflet-apk
          path: bin/*.apk  # Caminho padrão do Buildozer para o APK gerado