name: Build Flet Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-11-jdk
          pip install flet

      - name: Configurar ambiente Android
        run: |
          # Baixe e configure o SDK e NDK Android para a compilação
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME
          yes | $HOME/cmdline-tools/bin/sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"
          export ANDROID_HOME=$HOME/cmdline-tools

      - name: Compilar o APK
        run: |

          echo "Compilação do APK deve ser configurada."

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: /